<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PS8178" name="Sample Test Case" tests="8" failures="1" timestamp="3 Mar 2014 13:21:39 GMT" time="85.542" errors="0">
  <testcase name="test1" time="0.0" classname="TestCases.IgnoreTestMethod"/>
  <testcase name="test2" time="0.0" classname="TestCases.IgnoreTestMethod"/>
  <testcase name="TestuploadPic" time="0.0010" classname="TestCases.uploadPic"/>
  <testcase name="TestViewPic" time="0.0" classname="TestCases.uploadPic"/>
  <testcase name="login" time="28.413" classname="TestCases.actitime"/>
  <testcase name="timeoutmethd2" time="1.01" classname="TestCases.TimeOut">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.timeoutmethd2() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.timeoutmethd2() didn't finish within the time-out 1000
	at TestCases.TimeOut.timeoutmethd2(TimeOut.java:16)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:619)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- timeoutmethd2 -->
  <testcase name="timeoutmethod" time="4.0" classname="TestCases.TimeOut"/>
  <testcase name="TestLogin" time="44.807" classname="TestCases.LoginActitimeExcellSheet"/>
</testsuite> <!-- Sample Test Case -->
